In [1]:
#Task 2
import numpy as np

In [2]:
#Question 1
array_numbers = np.arange(10,50)
print(array_numbers)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [3]:
#Question 2
array_3d = np.arange(27).reshape(3,3,3)
print(array_3d)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


In [4]:
#Question 3
array_3d_identity = np.eye(3)
print(array_3d_identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
#Question 4
random_array = np.random.random()
mean = np.mean(random_array)
print(mean)

0.2159722625358692


In [6]:
#Question 5
random_array_10d = np.random.rand(10,20)
min_value = np.min(random_array_10d)
max_value = np.max(random_array_10d)
print(min_value)
print(max_value)

0.006348964867899043
0.9979654174127148


In [ ]:
#Question 6
zero_arrays = np.zeros(10)
zero_arrays[4] = 1
print(zero_arrays)

In [ ]:
#Question 7
arr = [1,2,0,0,4,0]
reverse_array = np.flip(arr)
print(reverse_array)

In [ ]:
#Question 8
new_array = np.zeros((4,4))
arranged_array = np.pad(new_array, pad_width=1,mode='constant',constant_values=1)
print(arranged_array)

In [ ]:
#Question 9
checkerboard = np.zeros((8,8))
checkerboard[1::2,::2] = 1
checkerboard[::2,1::2] = 1
print(checkerboard)